### ISSUE TITLE
Checkbox near leaf elements

### ISSUE THREAD

**Issue by orabin** [mt-ag/apex-fancytree-plugin#1]
How to use your plugin, so that checkboxes appear only next to the leaf elements?

**Comment by mt-ag** [comment]
Hey Orabin,
I'm currently working on making this declarative. It shouldn't take too long to implement this.
I'll write another comment here once I've uploaded the new version that contains this functionality. You just have to redownload the plug-in and it should work fine.

**Comment by mt-ag** [comment]
I updated the plug-in, so you should be able to use it now. You might have to download the new version from GitHub directly, since I have some troubles getting apex.world to update the plug-in.
Please tell me if it works correctly for your cause :)

**Comment by orabin** [comment]
I could not use your plugin.
Can I further describe how to bind variables to a query? Or get access to export your test application?

Thank you.
