### ISSUE TITLE
Setting default selected status

### ISSUE THREAD

**Issue by shaunmauer** [mt-ag/apex-fancytree-plugin#10]
Hi

Is it possible to set the selected status of a node at create/render time?

Possibly reuse the checked page item to set the `selected` value?

Regards
Shaun

**Comment by mt-ag** [comment]
Hey Shaun,
it is definitely possible to do this. You could either execute some JavaScript on page load, or add a setting to the "persist" module.
What exactly do you mean by "selected status"? Do you mean that the checkbox of a node is checked, or rather the blue-ish highlight when the user clicks a node? Once I know this I can help a bit more.

**Comment by shaunmauer** [comment]
Hi

If a checkbox is selected or not when the tree loads.
I have found a work around for now (hacked the plugin completely due to some specific requirements i have...)

Talking about that blue highlighting.. how can I disable it and still have the checkboxes?

Regards,

**Comment by mt-ag** [comment]
If you want to read the nodes from a page item, you could do the following:
`$("#tree2").fancytree("getTree").getNodeByKey("7839").setSelected(true);`
Where the jQuery selector points to your tree, and the key is the key from the node you want to select.
If you just want to "save" the selected nodes on a refresh, you'll have to add a word in the code. You'll find the following code in the plug-in:
```
persist: {
    cookiePrefix: ' || :APP_ID || :APP_PAGE_ID || regionid || ', //unique storage identifier for every tree
    expandLazy: true, //needed because of lazy loading
    store: "auto", //try sessionStorage, otherwise cookies
    types: "expanded" //only store expanded state
},
```
Change the last line to `types: "expanded selected"`

I'll look into how you can disable the blue highlight.

**Comment by mt-ag** [comment]
Hey Shaun,
removing the blue highlight is a bit of work. I only found [this solution](https://stackoverflow.com/questions/26024818/fancytree-remove-blue-border-when-selected). 
However, to do this, you'd have to change the included CSS file to the non-minified version.

**Comment by shaunmauer** [comment]
Hi

Found a solution by including the CSS in the Theme Roller Custom CSS.
The remove the highlighted row, the border around the table when focused, the border when it is active:

```
table.fancytree-ext-table > tbody > tr.fancytree-active {
	outline: none !important;
}

table.fancytree-ext-table.fancytree-treefocus > tbody > tr.fancytree-selected {
	background-color: #F7F7F7 !important;
}

table.fancytree-ext-table:focus {
	outline: none !important;
}
```
